//go:build !windows

package utils

import (
	"context"
	"encoding/json"
	"errors"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Fixture PAM files, modelled on what the distributions ship. The hook line
// is the one the alpamon-pam packages append.
const (
	alpamonHookBare = "\n# Alpamon session detection (non-Alpacon access events)\nsession optional pam_alpamon.so\n"
	alpamonHookAbs  = "\n# Alpamon session detection (non-Alpacon access events)\nsession optional /usr/lib64/security/pam_alpamon.so\n"

	debianCommonAuth     = "auth\t[success=1 default=ignore]\tpam_unix.so nullok\nauth\trequisite\t\t\tpam_deny.so\nauth\trequired\t\t\tpam_permit.so\n"
	debianCommonAccount  = "account\t[success=1 new_authtok_reqd=done default=ignore]\tpam_unix.so\naccount\trequisite\t\t\tpam_deny.so\n"
	debianCommonPassword = "password\t[success=1 default=ignore]\tpam_unix.so obscure yescrypt\npassword\trequisite\t\t\tpam_deny.so\n"
	debianCommonSession  = `#
# /etc/pam.d/common-session - session-related modules common to all services
#
session	[default=1]			pam_permit.so
session	requisite			pam_deny.so
session	required			pam_permit.so
session optional			pam_umask.so
session	required	pam_unix.so
session	optional	pam_systemd.so
`
	debianSSHD = `# PAM configuration for the Secure Shell service
@include common-auth
account    required     pam_nologin.so
@include common-account
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_keyinit.so force revoke
@include common-session
session    optional     pam_motd.so  motd=/run/motd.dynamic
session    optional     pam_mail.so standard noenv # [1]
session    required     pam_limits.so
@include common-password
`
	debianLogin = `auth       optional   pam_faildelay.so  delay=3000000
auth       requisite  pam_nologin.so
session [success=ok ignore=ignore module_unknown=ignore default=bad] pam_selinux.so close
session    required     pam_loginuid.so
@include common-auth
@include common-account
@include common-session
@include common-password
`
	debianSu = `auth       sufficient pam_rootok.so
session       required   pam_env.so readenv=1
session    optional   pam_mail.so nopen
session    required   pam_limits.so
@include common-auth
@include common-account
@include common-session
`

	rhelPasswordAuth = `#%PAM-1.0
# Generated by authselect
auth        required                                     pam_env.so
auth        sufficient                                   pam_unix.so nullok
auth        required                                     pam_deny.so
account     required                                     pam_unix.so
password    sufficient                                   pam_unix.so yescrypt shadow nullok use_authtok
session     optional                                     pam_keyinit.so revoke
session     required                                     pam_limits.so
-session    optional                                     pam_systemd.so
session     [success=1 default=ignore]                   pam_succeed_if.so service in crond quiet use_uid
session     required                                     pam_unix.so
`
	rhelPostlogin = `#%PAM-1.0
session     optional                   pam_umask.so silent
session     [success=1 default=ignore] pam_succeed_if.so service !~ gdm* service !~ su* quiet
session     [default=1]                pam_lastlog.so nowtmp showfailed
session     optional                   pam_lastlog.so silent noupdate showfailed
`
	rhelSSHD = `#%PAM-1.0
auth       substack     password-auth
auth       include      postlogin
account    required     pam_sepermit.so
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    optional     pam_motd.so
session    include      password-auth
session    include      postlogin
`
	rhelLogin = `#%PAM-1.0
auth       substack     system-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      system-auth
password   include      system-auth
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
session    include      postlogin
-session   optional     pam_ck_connector.so
`
	rhelSu = `#%PAM-1.0
auth		required	pam_env.so
auth		sufficient	pam_rootok.so
auth		substack	system-auth
auth		include		postlogin
account		sufficient	pam_succeed_if.so uid = 0 use_uid quiet
account		include		system-auth
password	include		system-auth
session		include		system-auth
session		include		postlogin
session		optional	pam_xauth.so
`
	rhelSuL = `#%PAM-1.0
auth		include		su
account		include		su
password	include		su
session		optional	pam_keyinit.so force revoke
session		include		su
`
)

const (
	debianModule = "/lib/x86_64-linux-gnu/security/pam_alpamon.so"
	rpmModule    = "/usr/lib64/security/pam_alpamon.so"
)

var (
	debianBins = []string{"/usr/sbin/sshd", "/usr/bin/login", "/usr/bin/su"}
	rhelBins   = []string{"/usr/sbin/sshd", "/usr/bin/login", "/usr/bin/su"}
)

func debianFiles() map[string]string {
	return map[string]string{
		"/etc/pam.d/common-auth":     debianCommonAuth,
		"/etc/pam.d/common-account":  debianCommonAccount,
		"/etc/pam.d/common-password": debianCommonPassword,
		"/etc/pam.d/common-session":  debianCommonSession,
		"/etc/pam.d/sshd":            debianSSHD + alpamonHookBare,
		"/etc/pam.d/login":           debianLogin + alpamonHookBare,
		"/etc/pam.d/su":              debianSu + alpamonHookBare,
		debianModule:                 "",
	}
}

func rhelFiles() map[string]string {
	return map[string]string{
		"/etc/pam.d/password-auth": rhelPasswordAuth,
		"/etc/pam.d/system-auth":   rhelPasswordAuth,
		"/etc/pam.d/postlogin":     rhelPostlogin,
		"/etc/pam.d/sshd":          rhelSSHD + alpamonHookAbs,
		"/etc/pam.d/login":         rhelLogin + alpamonHookAbs,
		"/etc/pam.d/su":            rhelSu + alpamonHookAbs,
		"/etc/pam.d/su-l":          rhelSuL + alpamonHookAbs,
		rpmModule:                  "",
	}
}

// with returns a copy of files with the given paths added or replaced.
func with(files map[string]string, changes map[string]string) map[string]string {
	out := maps.Clone(files)
	maps.Copy(out, changes)
	return out
}

func without(files map[string]string, paths ...string) map[string]string {
	out := with(files, nil)
	for _, p := range paths {
		delete(out, p)
	}
	return out
}

func buildLoginCaptureRoot(t *testing.T, files map[string]string, bins []string) string {
	t.Helper()
	root := t.TempDir()
	for p, content := range files {
		full := filepath.Join(root, p)
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte(content), 0o644))
	}
	for _, b := range bins {
		full := filepath.Join(root, b)
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte("#!/bin/false\n"), 0o755))
	}
	return root
}

// fakeSSHD stands in for `sshd -T` and counts its runs.
type fakeSSHD struct {
	out   string
	err   error
	runs  int
	panic bool
}

func (f *fakeSSHD) run(_ context.Context, _ string) ([]byte, error) {
	f.runs++
	if f.panic {
		panic("sshd runner exploded")
	}
	return []byte(f.out), f.err
}

// countingReader wraps os.ReadFile, counts reads and can fail chosen paths.
type countingReader struct {
	reads int
	fail  map[string]error
}

func (r *countingReader) read(path string) ([]byte, error) {
	r.reads++
	for suffix, err := range r.fail {
		if strings.HasSuffix(path, suffix) {
			return nil, err
		}
	}
	return os.ReadFile(path)
}

func newTestCollector(root string, sshd *fakeSSHD, reader *countingReader) *loginCaptureCollector {
	c := newLoginCaptureCollector(root)
	c.runSSHDT = sshd.run
	if reader != nil {
		c.readFile = reader.read
	}
	return c
}

func strPtr(s string) *string { return &s }

func TestLoginCaptureLayouts(t *testing.T) {
	usePAMYes := "port 22\nusepam yes\n"

	tests := []struct {
		name     string
		files    map[string]string
		bins     []string
		sshdOut  string
		sshdErr  error
		failRead map[string]error
		want     LoginCapture
	}{
		{
			name:    "debian with the hook in each service",
			files:   debianFiles(),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "debian with the hook only in an @include chain",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/sshd":                 debianSSHD,
				"/etc/pam.d/login":                debianLogin,
				"/etc/pam.d/su":                   debianSu,
				"/etc/pam.d/common-session":       debianCommonSession + "@include common-session-extra\n",
				"/etc/pam.d/common-session-extra": "session optional pam_alpamon.so\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "rhel with su-l including su and absolute module paths",
			files:   rhelFiles(),
			bins:    rhelBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered", SuL: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "rhel with the hook reached through substack and include",
			files: with(rhelFiles(), map[string]string{
				"/etc/pam.d/sshd":          strings.Replace(rhelSSHD, "session    include      password-auth", "session    substack     password-auth", 1),
				"/etc/pam.d/login":         rhelLogin,
				"/etc/pam.d/su":            rhelSu,
				"/etc/pam.d/su-l":          rhelSuL,
				"/etc/pam.d/password-auth": rhelPasswordAuth + "session optional pam_alpamon.so\n",
				"/etc/pam.d/system-auth":   rhelPasswordAuth + "session optional pam_alpamon.so\n",
			}),
			bins:    rhelBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered", SuL: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "rhel su-l without the hook and not including su's session",
			files: with(rhelFiles(), map[string]string{
				"/etc/pam.d/su-l": "auth include su\nsession optional pam_keyinit.so force revoke\nsession include postlogin\n",
			}),
			bins:    rhelBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered", SuL: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "vendor directory only",
			files: map[string]string{
				"/usr/lib/pam.d/common-session": "session required pam_unix.so\n",
				"/usr/lib/pam.d/sshd":           "session include common-session\n" + alpamonHookAbs,
				"/usr/lib/pam.d/login":          "session include common-session\n" + alpamonHookAbs,
				"/usr/lib/pam.d/su":             "session include common-session\n" + alpamonHookAbs,
				"/usr/lib/pam.d/su-l":           "session include su\n",
				rpmModule:                       "",
			},
			bins:    []string{"/usr/sbin/sshd", "/usr/bin/login", "/usr/bin/su"},
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered", SuL: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "usr/etc vendor directory",
			files: map[string]string{
				"/usr/etc/pam.d/sshd":  alpamonHookAbs,
				"/usr/etc/pam.d/login": alpamonHookAbs,
				"/usr/etc/pam.d/su":    alpamonHookAbs,
				rpmModule:              "",
			},
			bins:    []string{"/usr/sbin/sshd", "/usr/bin/login", "/usr/bin/su"},
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "etc copy shadows the vendor copy",
			files: map[string]string{
				"/etc/pam.d/sshd":      "session required pam_unix.so\n",
				"/usr/lib/pam.d/sshd":  alpamonHookAbs,
				"/usr/lib/pam.d/login": alpamonHookAbs,
				"/usr/lib/pam.d/su":    alpamonHookAbs,
				rpmModule:              "",
			},
			bins:    []string{"/usr/sbin/sshd", "/usr/bin/login", "/usr/bin/su"},
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "missing", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "hook present for sshd and login but missing for su",
			files:   with(debianFiles(), map[string]string{"/etc/pam.d/su": debianSu}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "bare module name in a non-gnu multiarch directory",
			files: with(without(debianFiles(), debianModule), map[string]string{
				"/usr/lib/arm-linux-gnueabihf/security/pam_alpamon.so": "",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "commented-out hook lines do not count",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/sshd":  debianSSHD + "#session optional pam_alpamon.so\n",
				"/etc/pam.d/login": debianLogin + "  # session optional pam_alpamon.so\n",
				"/etc/pam.d/su":    debianSu + "session optional pam_unix.so # pam_alpamon.so\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "missing", Login: "missing", Su: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "similar module names, non-session lines and the sudo stack do not count",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/sshd":  debianSSHD + "session optional pam_alpamon_legacy.so\n",
				"/etc/pam.d/login": debianLogin + "session optional /opt/pam_alpamon.so.bak\n",
				"/etc/pam.d/su":    debianSu + "auth [success=done default=ignore] pam_alpamon.so\n",
				"/etc/pam.d/sudo":  "session optional pam_alpamon.so\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "missing", Login: "missing", Su: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "control brackets, the dash prefix, case and line continuation",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/sshd":  debianSSHD + "session [success=ok default=ignore] pam_alpamon.so\n",
				"/etc/pam.d/login": debianLogin + "-session optional /lib/x86_64-linux-gnu/security/pam_alpamon.so\n",
				"/etc/pam.d/su":    debianSu + "Session optional \\\n    pam_alpamon.so\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "a comment ends a continued line",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/su": debianSu + "session optional # note \\\npam_alpamon.so\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "include loop is unreadable",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/su":     "session include loop-a\n" + alpamonHookBare,
				"/etc/pam.d/loop-a": "session include loop-b\n",
				"/etc/pam.d/loop-b": "@include loop-a\n",
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "unreadable"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "the same file included twice is not a loop",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/su": debianSu + "@include common-session\n" + alpamonHookBare,
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "include past the depth limit is unreadable",
			files: func() map[string]string {
				files := with(debianFiles(), nil)
				files["/etc/pam.d/su"] = "session include chain-0\n" + alpamonHookBare
				for i := range 20 {
					files["/etc/pam.d/chain-"+strconv.Itoa(i)] = "session include chain-" + strconv.Itoa(i+1) + "\n"
				}
				files["/etc/pam.d/chain-20"] = "session required pam_unix.so\n"
				return files
			}(),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "unreadable"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "missing include target is unreadable",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/su": "session include does-not-exist\n" + alpamonHookBare,
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "unreadable"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:     "file that cannot be read is unreadable",
			files:    debianFiles(),
			bins:     debianBins,
			sshdOut:  usePAMYes,
			failRead: map[string]error{"/etc/pam.d/login": fs.ErrPermission},
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "unreadable", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:     "included file that cannot be read is unreadable",
			files:    debianFiles(),
			bins:     debianBins,
			sshdOut:  usePAMYes,
			failRead: map[string]error{"/etc/pam.d/common-session": fs.ErrPermission},
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "unreadable", Login: "unreadable", Su: "unreadable"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "service binary absent and no PAM file is not applicable",
			files:   without(debianFiles(), "/etc/pam.d/login"),
			bins:    []string{"/usr/sbin/sshd", "/usr/bin/su"},
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "not_applicable", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "service binary present without a PAM file is unreadable",
			files:   without(debianFiles(), "/etc/pam.d/su"),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "unreadable"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "sshd present without a PAM file keeps its UsePAM answer",
			files:   without(debianFiles(), "/etc/pam.d/sshd"),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "unreadable", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "UsePAM no",
			files:   debianFiles(),
			bins:    debianBins,
			sshdOut: "usepam no\n",
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("no")},
		},
		{
			name:    "sshd -T failing reports null",
			files:   debianFiles(),
			bins:    debianBins,
			sshdErr: errors.New("exit status 255"),
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks: LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"}},
		},
		{
			name:    "sshd absent",
			files:   without(debianFiles(), "/etc/pam.d/sshd"),
			bins:    []string{"/usr/bin/login", "/usr/bin/su"},
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks: LoginCaptureHooks{SSHD: "not_applicable", Login: "registered", Su: "registered"}},
		},
		{
			name:    "module file missing",
			files:   without(debianFiles(), debianModule),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "missing",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:    "absolute module path that does not exist",
			files:   with(without(rhelFiles(), rpmModule), map[string]string{"/usr/lib/security/pam_alpamon.so": ""}),
			bins:    rhelBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "missing",
				Hooks:      LoginCaptureHooks{SSHD: "registered", Login: "registered", Su: "registered", SuL: "registered"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name: "module installed but no hook anywhere",
			files: with(debianFiles(), map[string]string{
				"/etc/pam.d/sshd":  debianSSHD,
				"/etc/pam.d/login": debianLogin,
				"/etc/pam.d/su":    debianSu,
			}),
			bins:    debianBins,
			sshdOut: usePAMYes,
			want: LoginCapture{Schema: 1, PAMModule: "present",
				Hooks:      LoginCaptureHooks{SSHD: "missing", Login: "missing", Su: "missing"},
				SSHDUsePAM: strPtr("yes")},
		},
		{
			name:  "nothing installed",
			files: map[string]string{},
			want: LoginCapture{Schema: 1, PAMModule: "missing",
				Hooks: LoginCaptureHooks{SSHD: "not_applicable", Login: "not_applicable", Su: "not_applicable"}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := buildLoginCaptureRoot(t, tt.files, tt.bins)
			sshd := &fakeSSHD{out: tt.sshdOut, err: tt.sshdErr}
			c := newTestCollector(root, sshd, &countingReader{fail: tt.failRead})

			got := c.Get()
			require.NotNil(t, got)
			assert.Equal(t, tt.want, *got)
		})
	}
}

// TestLoginCaptureSSHDNotRunWithoutSSHD makes sure an sshd-less host never
// forks anything.
func TestLoginCaptureSSHDNotRunWithoutSSHD(t *testing.T) {
	root := buildLoginCaptureRoot(t, without(debianFiles(), "/etc/pam.d/sshd"), []string{"/usr/bin/su"})
	sshd := &fakeSSHD{out: "usepam yes\n"}
	c := newTestCollector(root, sshd, nil)

	got := c.Get()
	require.NotNil(t, got)
	assert.Nil(t, got.SSHDUsePAM)
	assert.Equal(t, 0, sshd.runs)
}

// TestLoginCaptureUnreadableByPermission uses a real mode-000 file; root
// reads through it, so the case is skipped there.
func TestLoginCaptureUnreadableByPermission(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root reads a mode-000 file")
	}
	root := buildLoginCaptureRoot(t, debianFiles(), debianBins)
	su := filepath.Join(root, "etc/pam.d/su")
	require.NoError(t, os.Chmod(su, 0))
	t.Cleanup(func() { _ = os.Chmod(su, 0o644) })

	c := newTestCollector(root, &fakeSSHD{out: "usepam yes\n"}, nil)
	got := c.Get()
	require.NotNil(t, got)
	assert.Equal(t, HookUnreadable, got.Hooks.Su)
	assert.Equal(t, HookRegistered, got.Hooks.SSHD)
}

// TestLoginCaptureNonRegularFile guards against blocking on a FIFO or reading
// a directory where a PAM file should be.
func TestLoginCaptureNonRegularFile(t *testing.T) {
	root := buildLoginCaptureRoot(t, without(debianFiles(), "/etc/pam.d/su"), debianBins)
	require.NoError(t, os.Mkdir(filepath.Join(root, "etc/pam.d/su"), 0o755))

	c := newTestCollector(root, &fakeSSHD{out: "usepam yes\n"}, nil)
	got := c.Get()
	require.NotNil(t, got)
	assert.Equal(t, HookUnreadable, got.Hooks.Su)
}

func TestLoginCaptureCache(t *testing.T) {
	files := with(debianFiles(), map[string]string{"/etc/ssh/sshd_config": "UsePAM yes\n"})
	root := buildLoginCaptureRoot(t, files, debianBins)
	sshd := &fakeSSHD{out: "usepam yes\n"}
	reader := &countingReader{}
	c := newTestCollector(root, sshd, reader)

	first := c.Get()
	require.NotNil(t, first)
	assert.Equal(t, 1, sshd.runs)
	firstReads := reader.reads
	assert.Positive(t, firstReads)

	// Nothing changed: no file is read again and sshd -T is not re-run.
	second := c.Get()
	require.NotNil(t, second)
	assert.Equal(t, *first, *second)
	assert.Equal(t, firstReads, reader.reads, "unchanged PAM files must come from the cache")
	assert.Equal(t, 1, sshd.runs, "unchanged sshd config must not re-run sshd -T")

	// A changed PAM file is read again, and only that file.
	later := time.Now().Add(time.Hour)
	su := filepath.Join(root, "etc/pam.d/su")
	require.NoError(t, os.WriteFile(su, []byte(debianSu), 0o644))
	require.NoError(t, os.Chtimes(su, later, later))
	third := c.Get()
	require.NotNil(t, third)
	assert.Equal(t, HookMissing, third.Hooks.Su)
	assert.Equal(t, firstReads+1, reader.reads)
	assert.Equal(t, 1, sshd.runs)

	// A changed sshd_config re-runs sshd -T.
	sshd.out = "usepam no\n"
	cfg := filepath.Join(root, "etc/ssh/sshd_config")
	require.NoError(t, os.Chtimes(cfg, later, later))
	fourth := c.Get()
	require.NotNil(t, fourth)
	assert.Equal(t, 2, sshd.runs)
	assert.Equal(t, strPtr("no"), fourth.SSHDUsePAM)

	// So does a new drop-in under sshd_config.d.
	dropIn := filepath.Join(root, "etc/ssh/sshd_config.d/50-cloud.conf")
	require.NoError(t, os.MkdirAll(filepath.Dir(dropIn), 0o755))
	require.NoError(t, os.WriteFile(dropIn, []byte("UsePAM yes\n"), 0o644))
	sshd.out = "usepam yes\n"
	fifth := c.Get()
	require.NotNil(t, fifth)
	assert.Equal(t, 3, sshd.runs)
	assert.Equal(t, strPtr("yes"), fifth.SSHDUsePAM)

	// And a replaced sshd binary.
	bin := filepath.Join(root, "usr/sbin/sshd")
	require.NoError(t, os.Chtimes(bin, later, later))
	c.Get()
	assert.Equal(t, 4, sshd.runs)
}

func TestLoginCaptureSSHDRecheckAfterFailureAndAge(t *testing.T) {
	root := buildLoginCaptureRoot(t, debianFiles(), debianBins)
	sshd := &fakeSSHD{err: errors.New("missing privilege separation directory")}
	c := newTestCollector(root, sshd, nil)
	now := time.Now()
	c.now = func() time.Time { return now }

	assert.Nil(t, c.Get().SSHDUsePAM)
	assert.Equal(t, 1, sshd.runs)

	// A failed check is not retried on every report...
	now = now.Add(sshdUsePAMRetryAfter - time.Minute)
	c.Get()
	assert.Equal(t, 1, sshd.runs)

	// ...but it is retried after the retry interval.
	now = now.Add(2 * time.Minute)
	c.Get()
	assert.Equal(t, 2, sshd.runs)

	// The privilege separation directory appearing re-runs it at once.
	sshd.err, sshd.out = nil, "usepam yes\n"
	require.NoError(t, os.MkdirAll(filepath.Join(root, "run/sshd"), 0o755))
	assert.Equal(t, strPtr("yes"), c.Get().SSHDUsePAM)
	assert.Equal(t, 3, sshd.runs)

	// A successful answer is re-checked once it is old, even with no change on disk.
	now = now.Add(sshdUsePAMMaxAge - time.Minute)
	c.Get()
	assert.Equal(t, 3, sshd.runs)
	now = now.Add(2 * time.Minute)
	c.Get()
	assert.Equal(t, 4, sshd.runs)
}

func TestLoginCaptureReturnedValueIsACopy(t *testing.T) {
	root := buildLoginCaptureRoot(t, debianFiles(), debianBins)
	c := newTestCollector(root, &fakeSSHD{out: "usepam yes\n"}, nil)

	first := c.Get()
	require.NotNil(t, first)
	*first.SSHDUsePAM = "no"
	assert.Equal(t, strPtr("yes"), c.Get().SSHDUsePAM)
}

func TestLoginCaptureSerializedShapeAndSize(t *testing.T) {
	root := buildLoginCaptureRoot(t, rhelFiles(), rhelBins)
	c := newTestCollector(root, &fakeSSHD{out: "usepam yes\n"}, nil)
	got := c.Get()
	require.NotNil(t, got)

	data, err := json.Marshal(got)
	require.NoError(t, err)
	assert.JSONEq(t, `{
		"schema": 1,
		"pam_module": "present",
		"hooks": {"sshd": "registered", "login": "registered", "su": "registered", "su-l": "registered"},
		"sshd_use_pam": "yes"
	}`, string(data))
	assert.Less(t, len(data), 512, "the server reads the block only up to 4 KiB")

	// su-l is absent where the host has no separate su-l file, and an
	// undeterminable UsePAM is an explicit null.
	data, err = json.Marshal(LoginCapture{Schema: 1, PAMModule: "missing",
		Hooks: LoginCaptureHooks{SSHD: "not_applicable", Login: "missing", Su: "unreadable"}})
	require.NoError(t, err)
	assert.JSONEq(t, `{
		"schema": 1,
		"pam_module": "missing",
		"hooks": {"sshd": "not_applicable", "login": "missing", "su": "unreadable"},
		"sshd_use_pam": null
	}`, string(data))
}

// TestLoginCapturePanicIsContained checks that a failure inside the
// collector yields no block instead of reaching the report, and that the
// collector works again afterwards.
func TestLoginCapturePanicIsContained(t *testing.T) {
	root := buildLoginCaptureRoot(t, debianFiles(), debianBins)

	sshd := &fakeSSHD{out: "usepam yes\n", panic: true}
	c := newTestCollector(root, sshd, nil)
	var got *LoginCapture
	assert.NotPanics(t, func() { got = c.Get() })
	assert.Nil(t, got)

	c = newTestCollector(root, &fakeSSHD{out: "usepam yes\n"}, nil)
	c.readFile = func(string) ([]byte, error) { panic("read exploded") }
	assert.NotPanics(t, func() { got = c.Get() })
	assert.Nil(t, got)

	c.readFile = os.ReadFile
	got = c.Get()
	require.NotNil(t, got, "a contained failure must not wedge the collector")
	assert.Equal(t, HookRegistered, got.Hooks.SSHD)
}
