version: 2

project_name: alpamon

before:
  hooks:
    - go run -mod=mod entgo.io/ent/cmd/ent@v0.14.2 generate --feature sql/modifier --target ./pkg/db/ent ./pkg/db/schema
    - go mod tidy

builds:
  - main: ./cmd/alpamon
    binary: alpamon
    ldflags:
      - -s -w -X github.com/alpacax/alpamon/pkg/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: '{{ .ProjectName }}-{{ trimprefix .Version "v" }}-checksums.sha256'

archives:
  - id: alpamon
    name_template: '{{ .ProjectName }}-{{ trimprefix .Version "v" }}-{{ .Os }}-{{ .Arch }}'

nfpms:
  - package_name: alpamon
    maintainer: AlpacaX <support@alpacax.com>
    description: Alpamon
    homepage: https://github.com/alpacax/alpamon
    license: MIT
    vendor: AlpacaX
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin/

    contents:
      - src: "configs/tmpfile.conf"
        dst: "/usr/lib/tmpfiles.d/{{ .ProjectName }}.conf"

      - src: "configs/{{ .ProjectName }}.conf"
        dst: "/etc/alpamon/{{ .ProjectName }}.config.tmpl"

      - src: "configs/{{ .ProjectName }}.service"
        dst: "/lib/systemd/system/{{ .ProjectName }}.service"

      - src: "configs/{{ .ProjectName }}-restart.service"
        dst: "/lib/systemd/system/{{ .ProjectName }}-restart.service"

      - src: "configs/{{ .ProjectName }}-restart.timer"
        dst: "/lib/systemd/system/{{ .ProjectName }}-restart.timer"

    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

    overrides:
      deb:
        dependencies:
          - zip
          - sqlite3
          - nftables | iptables
        file_name_template: '{{ .PackageName }}_{{ trimprefix .Version "v" }}_{{ .Os }}_{{ .Arch }}'
        suggests:
          - alpamon-pam
      rpm:
        dependencies:
          - zip
          - sqlite
          - nftables | iptables
        file_name_template: '{{ .PackageName }}-{{ trimprefix .Version "v" }}-1.{{ .Os }}.{{ .Arch }}'
        suggests:
          - alpamon-pam
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"