version: 2

project_name: alpamon

before:
  hooks:
    - go run -mod=mod entgo.io/ent/cmd/ent@v0.14.2 generate --feature sql/modifier --target ./pkg/db/ent ./pkg/db/schema
    - go mod tidy
    - chmod +x ./scripts/install_atlas.sh

builds:
  - main: ./cmd/alpamon
    binary: alpamon
    ldflags:
      - -s -w -X github.com/alpacax/alpamon/pkg/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - ./scripts/install_atlas.sh {{ .Arch }}

checksum:
  name_template: '{{ .ProjectName }}-{{ trimprefix .Version "v" }}-checksums.sha256'

archives:
  - id: alpamon
    name_template: '{{ .ProjectName }}-{{ trimprefix .Version "v" }}-{{ .Os }}-{{ .Arch }}'
    files:
      - src: bin/atlas-{{ .Arch }}
        dst: usr/local/bin/atlas

nfpms:
  - file_name_template: '{{ .PackageName }}_{{ trimprefix .Version "v" }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    package_name: alpamon
    maintainer: AlpacaX <support@alpacax.com>
    description: Alpamon
    homepage: https://github.com/alpacax/alpamon
    license: MIT
    vendor: AlpacaX
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin/

    contents:
      - src: "configs/tmpfile.conf"
        dst: "/usr/lib/tmpfiles.d/{{ .ProjectName }}.conf"

      - src: "configs/{{ .ProjectName }}.conf"
        dst: "/etc/alpamon/{{ .ProjectName }}.config.tmpl"

      - src: "configs/{{ .ProjectName }}.service"
        dst: "/lib/systemd/system/{{ .ProjectName }}.service"

      - src: "configs/{{ .ProjectName }}-restart.service"
        dst: "/lib/systemd/system/{{ .ProjectName }}-restart.service"

      - src: "configs/{{ .ProjectName }}-restart.timer"
        dst: "/lib/systemd/system/{{ .ProjectName }}-restart.timer"
      
      - src: "bin/atlas-{{ .Arch }}"
        dst: "/usr/local/bin/atlas"

    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

    overrides:
      deb:
        dependencies:
          - zip
          - sqlite3
      rpm:
        dependencies:
          - zip
          - sqlite
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"