d   /etc/alpamon                    0700    root root - -
d   /var/lib/alpamon                0750    root root - -
d   /var/log/alpamon                0750    root root - -
d   /run/alpamon                    0750    root root - -
